/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ToolsCertificatesRouteImport } from './routes/tools/certificates'
import { Route as ToolsExcelCertificatesRouteImport } from './routes/tools/excel-certificates'
import { Route as ToolsFontsRouteImport } from './routes/tools/fonts'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools/image-compressor'
import { Route as ToolsPdfRouteImport } from './routes/tools/pdf'
import { Route as ApiPublicAdImageNameRouteImport } from './routes/api/public/ad-image.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCertificatesRoute = ToolsCertificatesRouteImport.update({
  id: '/tools/certificates',
  path: '/tools/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsExcelCertificatesRoute = ToolsExcelCertificatesRouteImport.update({
  id: '/tools/excel-certificates',
  path: '/tools/excel-certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFontsRoute = ToolsFontsRouteImport.update({
  id: '/tools/fonts',
  path: '/tools/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfRoute = ToolsPdfRouteImport.update({
  id: '/tools/pdf',
  path: '/tools/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdImageNameRoute = ApiPublicAdImageNameRouteImport.update({
  id: '/api/public/ad-image/$name',
  path: '/api/public/ad-image/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/tools/certificates': typeof ToolsCertificatesRoute
  '/tools/excel-certificates': typeof ToolsExcelCertificatesRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/api/public/ad-image/$name': typeof ApiPublicAdImageNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/tools/certificates': typeof ToolsCertificatesRoute
  '/tools/excel-certificates': typeof ToolsExcelCertificatesRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/api/public/ad-image/$name': typeof ApiPublicAdImageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/tools/certificates': typeof ToolsCertificatesRoute
  '/tools/excel-certificates': typeof ToolsExcelCertificatesRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/api/public/ad-image/$name': typeof ApiPublicAdImageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/updates'
    | '/tools/certificates'
    | '/tools/excel-certificates'
    | '/tools/fonts'
    | '/tools/image-compressor'
    | '/tools/pdf'
    | '/api/public/ad-image/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/settings'
    | '/updates'
    | '/tools/certificates'
    | '/tools/excel-certificates'
    | '/tools/fonts'
    | '/tools/image-compressor'
    | '/tools/pdf'
    | '/api/public/ad-image/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/settings'
    | '/updates'
    | '/tools/certificates'
    | '/tools/excel-certificates'
    | '/tools/fonts'
    | '/tools/image-compressor'
    | '/tools/pdf'
    | '/api/public/ad-image/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SettingsRoute: typeof SettingsRoute
  UpdatesRoute: typeof UpdatesRoute
  ToolsCertificatesRoute: typeof ToolsCertificatesRoute
  ToolsExcelCertificatesRoute: typeof ToolsExcelCertificatesRoute
  ToolsFontsRoute: typeof ToolsFontsRoute
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsPdfRoute: typeof ToolsPdfRoute
  ApiPublicAdImageNameRoute: typeof ApiPublicAdImageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/certificates': {
      id: '/tools/certificates'
      path: '/tools/certificates'
      fullPath: '/tools/certificates'
      preLoaderRoute: typeof ToolsCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/excel-certificates': {
      id: '/tools/excel-certificates'
      path: '/tools/excel-certificates'
      fullPath: '/tools/excel-certificates'
      preLoaderRoute: typeof ToolsExcelCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/fonts': {
      id: '/tools/fonts'
      path: '/tools/fonts'
      fullPath: '/tools/fonts'
      preLoaderRoute: typeof ToolsFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf': {
      id: '/tools/pdf'
      path: '/tools/pdf'
      fullPath: '/tools/pdf'
      preLoaderRoute: typeof ToolsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad-image/$name': {
      id: '/api/public/ad-image/$name'
      path: '/api/public/ad-image/$name'
      fullPath: '/api/public/ad-image/$name'
      preLoaderRoute: typeof ApiPublicAdImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SettingsRoute: SettingsRoute,
  UpdatesRoute: UpdatesRoute,
  ToolsCertificatesRoute: ToolsCertificatesRoute,
  ToolsExcelCertificatesRoute: ToolsExcelCertificatesRoute,
  ToolsFontsRoute: ToolsFontsRoute,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsPdfRoute: ToolsPdfRoute,
  ApiPublicAdImageNameRoute: ApiPublicAdImageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
