/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ToolsCertificatesRouteImport } from './routes/tools/certificates'
import { Route as ToolsExamBuilderRouteImport } from './routes/tools/exam-builder'
import { Route as ToolsExcelCertificatesRouteImport } from './routes/tools/excel-certificates'
import { Route as ToolsFontsRouteImport } from './routes/tools/fonts'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools/image-compressor'
import { Route as ToolsPdfRouteImport } from './routes/tools/pdf'
import { Route as ApiPublicAdImageNameRouteImport } from './routes/api/public/ad-image.$name'
import { Route as ApiPublicArticleImageNameRouteImport } from './routes/api/public/article-image.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCertificatesRoute = ToolsCertificatesRouteImport.update({
  id: '/tools/certificates',
  path: '/tools/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsExamBuilderRoute = ToolsExamBuilderRouteImport.update({
  id: '/tools/exam-builder',
  path: '/tools/exam-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsExcelCertificatesRoute = ToolsExcelCertificatesRouteImport.update({
  id: '/tools/excel-certificates',
  path: '/tools/excel-certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFontsRoute = ToolsFontsRouteImport.update({
  id: '/tools/fonts',
  path: '/tools/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfRoute = ToolsPdfRouteImport.update({
  id: '/tools/pdf',
  path: '/tools/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdImageNameRoute = ApiPublicAdImageNameRouteImport.update({
  id: '/api/public/ad-image/$name',
  path: '/api/public/ad-image/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticleImageNameRoute =
  ApiPublicArticleImageNameRouteImport.update({
    id: '/api/public/article-image/$name',
    path: '/api/public/article-image/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/tools/certificates': typeof ToolsCertificatesRoute
  '/tools/exam-builder': typeof ToolsExamBuilderRoute
  '/tools/excel-certificates': typeof ToolsExcelCertificatesRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/public/ad-image/$name': typeof ApiPublicAdImageNameRoute
  '/api/public/article-image/$name': typeof ApiPublicArticleImageNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/tools/certificates': typeof ToolsCertificatesRoute
  '/tools/exam-builder': typeof ToolsExamBuilderRoute
  '/tools/excel-certificates': typeof ToolsExcelCertificatesRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/articles': typeof ArticlesIndexRoute
  '/api/public/ad-image/$name': typeof ApiPublicAdImageNameRoute
  '/api/public/article-image/$name': typeof ApiPublicArticleImageNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/settings': typeof SettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/tools/certificates': typeof ToolsCertificatesRoute
  '/tools/exam-builder': typeof ToolsExamBuilderRoute
  '/tools/excel-certificates': typeof ToolsExcelCertificatesRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/public/ad-image/$name': typeof ApiPublicAdImageNameRoute
  '/api/public/article-image/$name': typeof ApiPublicArticleImageNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/articles/$slug'
    | '/tools/certificates'
    | '/tools/exam-builder'
    | '/tools/excel-certificates'
    | '/tools/fonts'
    | '/tools/image-compressor'
    | '/tools/pdf'
    | '/articles/'
    | '/api/public/ad-image/$name'
    | '/api/public/article-image/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/settings'
    | '/articles/$slug'
    | '/tools/certificates'
    | '/tools/exam-builder'
    | '/tools/excel-certificates'
    | '/tools/fonts'
    | '/tools/image-compressor'
    | '/tools/pdf'
    | '/articles'
    | '/api/public/ad-image/$name'
    | '/api/public/article-image/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/settings'
    | '/articles/$slug'
    | '/tools/certificates'
    | '/tools/exam-builder'
    | '/tools/excel-certificates'
    | '/tools/fonts'
    | '/tools/image-compressor'
    | '/tools/pdf'
    | '/articles/'
    | '/api/public/ad-image/$name'
    | '/api/public/article-image/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SettingsRoute: typeof SettingsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ToolsCertificatesRoute: typeof ToolsCertificatesRoute
  ToolsExamBuilderRoute: typeof ToolsExamBuilderRoute
  ToolsExcelCertificatesRoute: typeof ToolsExcelCertificatesRoute
  ToolsFontsRoute: typeof ToolsFontsRoute
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsPdfRoute: typeof ToolsPdfRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiPublicAdImageNameRoute: typeof ApiPublicAdImageNameRoute
  ApiPublicArticleImageNameRoute: typeof ApiPublicArticleImageNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/certificates': {
      id: '/tools/certificates'
      path: '/tools/certificates'
      fullPath: '/tools/certificates'
      preLoaderRoute: typeof ToolsCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/exam-builder': {
      id: '/tools/exam-builder'
      path: '/tools/exam-builder'
      fullPath: '/tools/exam-builder'
      preLoaderRoute: typeof ToolsExamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/excel-certificates': {
      id: '/tools/excel-certificates'
      path: '/tools/excel-certificates'
      fullPath: '/tools/excel-certificates'
      preLoaderRoute: typeof ToolsExcelCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/fonts': {
      id: '/tools/fonts'
      path: '/tools/fonts'
      fullPath: '/tools/fonts'
      preLoaderRoute: typeof ToolsFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf': {
      id: '/tools/pdf'
      path: '/tools/pdf'
      fullPath: '/tools/pdf'
      preLoaderRoute: typeof ToolsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad-image/$name': {
      id: '/api/public/ad-image/$name'
      path: '/api/public/ad-image/$name'
      fullPath: '/api/public/ad-image/$name'
      preLoaderRoute: typeof ApiPublicAdImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article-image/$name': {
      id: '/api/public/article-image/$name'
      path: '/api/public/article-image/$name'
      fullPath: '/api/public/article-image/$name'
      preLoaderRoute: typeof ApiPublicArticleImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SettingsRoute: SettingsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ToolsCertificatesRoute: ToolsCertificatesRoute,
  ToolsExamBuilderRoute: ToolsExamBuilderRoute,
  ToolsExcelCertificatesRoute: ToolsExcelCertificatesRoute,
  ToolsFontsRoute: ToolsFontsRoute,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsPdfRoute: ToolsPdfRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiPublicAdImageNameRoute: ApiPublicAdImageNameRoute,
  ApiPublicArticleImageNameRoute: ApiPublicArticleImageNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
